### ISSUE TITLE
Unable to start keycloak on AWS EKS cluster

### ISSUE THREAD

**Issue by abhishekraghav** [galexrt/kubernetes-keycloak#2]
Hi,

I am fairly new  on Kubernetes, When i run this command:
`kubectl create -f . --namespace default`
But I am getting this error when i see the logs.
$ kubectl logs statefulsets/keycloak -n default

```
Starting with args:
==> I am instance number: 0
===> Checking instance: keycloak-0
curl: (6) Could not resolve host: keycloak-0.keycloak; Name or service not known
===> Failed! Hostname keycloak-0 unreachable.
=> Keycloak Hosts:
Added user 'keycloak' to file '/opt/jboss/keycloak/standalone/configuration/mgmt-users.properties'
Added user 'keycloak' to file '/opt/jboss/keycloak/domain/configuration/mgmt-users.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/standalone/configuration/mgmt-groups.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/domain/configuration/mgmt-groups.properties'
Added 'keycloak' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
[KEYCLOAK DOCKER IMAGE] Using the external postgres database
13:12:22,878 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
13:12:23,260 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
/opt/jboss/keycloak/bin/change-database.sh: line 7:   135 Killed                  bin/jboss-cli.sh --file=cli/databases/$DB_VENDOR/standalone-configuration.cli
13:12:27,366 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
13:12:27,751 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
/opt/jboss/keycloak/bin/change-database.sh: line 10:   190 Killed                  bin/jboss-cli.sh --file=cli/databases/$DB_VENDOR/standalone-ha-configuration.cli
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

13:12:30,451 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
13:12:31,755 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
13:12:32,171 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: Keycloak 3.4.3.Final (WildFly Core 3.0.8.Final) starting
13:12:32,360 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
*** JBossAS process (298) received KILL signal ***


```
Also the readiness probe is fails with the below message:

![image](https://user-images.githubusercontent.com/19988460/43677023-fbc5b750-9818-11e8-89d2-9076eab6c8bf.png)

Please let me know, whats going wrong here.

Thanks in advance.

**Comment by galexrt** [comment]
@abhishekraghav Try increasing the readiness and liveness probe initial timeout.
Also did you set the database address correctly or is the database a bit slow causing the probes timeouts to be reached?

**Comment by abhishekraghav** [comment]
Thanks for the quick response. 
It worked. In the beginning it was failing but eventually it started working. May be due to timeout setting.
**I did two changes following your suggestion:-**

- Changed the timeoutSeconds to 60 sec from 1 sec and introduced timeout setting in liveliness probe.
- Commented out this line in configmap.yml.  #POSTGRES_HOST: sinfra-stolon-proxy.zerbytes-live-svc-db-postgres.svc, since I was not sure what that mean.

**Now I am not sure which setting worked.**

But I found that I am still seeing that the host resolution is failing.
 e.g. curl: (6) Could not resolve host: keycloak-0.keycloak; Name or service not known
===&gt; Failed! Hostname keycloak-0 unreachable.

Please find logs keycloak-0 pod below:

```
Starting with args: 
==&gt; I am instance number: 0
===&gt; Checking instance: keycloak-0
curl: (6) Could not resolve host: keycloak-0.keycloak; Name or service not known
===&gt; Failed! Hostname keycloak-0 unreachable.
=&gt; Keycloak Hosts: 
Added user 'keycloak' to file '/opt/jboss/keycloak/standalone/configuration/mgmt-users.properties'
Added user 'keycloak' to file '/opt/jboss/keycloak/domain/configuration/mgmt-users.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/standalone/configuration/mgmt-groups.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/domain/configuration/mgmt-groups.properties'
Added 'keycloak' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
```

Logs from keycloak-1 pod, I got a success message here. 
```
tarting with args: 
==&gt; I am instance number: 1
===&gt; Checking instance: keycloak-0
===&gt; Success! Hostname keycloak-0 reachable.
===&gt; Checking instance: keycloak-1
curl: (6) Could not resolve host: keycloak-1.keycloak; Name or service not known
===&gt; Failed! Hostname keycloak-1 unreachable.
=&gt; Keycloak Hosts: keycloak-0.keycloak[7600]
Added user 'keycloak' to file '/opt/jboss/keycloak/standalone/configuration/mgmt-users.properties'
Added user 'keycloak' to file '/opt/jboss/keycloak/domain/configuration/mgmt-users.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/standalone/configuration/mgmt-groups.properties'


```

I want to understand what is this for. What the script does actually..?
And does this setup provide HA (high availability), Do we have any string in the logs which can prove that keycloak is started with HA mode. 

Thanks a lot again.
Cheers.

**Comment by galexrt** [comment]
@abhishekraghav The script is trying to detect the other instances by iterating over the instance number it has, e.g. if keycloak-0 starts it tries to resolve keycloak-0's IP and fails because a StatefulSet (default) is to not "create" the DNS entry for the Pod until it is ready, which is okay in that case.

The keycloak-1 instance starts sees that it is number "2" and then iterates beginning from 0 to 1 and with that then successfully detects the first keycloak instance (keycloak-0).

You can see that it was successful when the logs print that the other peer has connected to each other through jgroups `TCPPING`.

**Comment by abhishekraghav** [comment]
@galexrt 
Thanks for the clarification. I guess both the nodes are HA by looking at this part of logs.

`[0m16:36:31,787 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-5) ISPN000094: Received new cluster view for channel ee: [keycloak-0|1] (2) [keycloak-0, keycloak-1]
`
I had one more question to ask.

I guess this setup is terminating SSL on loadbalancer and from load balancer to pod as plain text, Thus  not propagating the encryption of data till the actual node.

Is there a way by which i can  encrypt the complete channel and not terminate SSL on NGINX which is happening right now I guess.

What changes would I be looking in terms of configuration to have such a setup.

Thanks.

**Comment by galexrt** [comment]
@abhishekraghav Yes the setup is terminating SSL at the LB.
You would need to add a mount of the certs to the Keycloak StatefulSet and tell your Ingress Controller to let SSL "passthrough" and also go to the "backend" (Keycloak Service).
Additionally you need to modify the Keycloak "config file" `standalone-ha.xml` (the config used here can be found here https://github.com/galexrt/kubernetes-keycloak/blob/master/configmap.yaml#L60-L706) to use the certs/keystore for more info on that please consult the Keycloak documentation:
* https://www.keycloak.org/docs/latest/server_admin/index.html#_ssl_modes
* https://www.keycloak.org/docs/latest/server_admin/index.html#enable-x-509-client-certificate-user-authentication
* Probably some other places that have some details on keystore creation (from Keycloak 3.3 docs: https://www.keycloak.org/docs/3.3/server_installation/topics/network/https.html)

**Comment by abhishekraghav** [comment]
Hi @galexrt 
Thanks for clarification. I will make necessary changes in statefulset to mount the SSL certificates.

I actually one more error since yesterday, I am seeing  308 Permanent Redirect continuously whenever I am hitting my auth server URL.

Everything was working fine till yesterday evening and then eventually started coming. I am not seeing any issues on the service , pod etc. Looks like this error is being returned by NGINX. 

What could be the problem..

Attaching the screenshot for your reference:-
![image](https://user-images.githubusercontent.com/19988460/43756070-aa490bd8-9a30-11e8-8d72-6c31197a5e45.png)

**Comment by abhishekraghav** [comment]
@galexrt 
# Update 
I found an issue in my ingress, I had a variation in my ingress configuration i.e. I did set different values for hosts and host key.

Old ingress config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-examplecom
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - keycloak.example.com
    secretName: tls-com-example-keycloak
  rules:
  - host: keycloak.secdev.pocpcf.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-external
          servicePort: 8080
      - path: /auth
        backend:
          serviceName: keycloak-external
          servicePort: 8080

```

New Ingess Configuration (Kept hosts and host as same only)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-examplecom
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - keycloak.secdev.pocpcf.com
    secretName: tls-com-example-keycloak
  rules:
  - host: keycloak.secdev.pocpcf.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-external
          servicePort: 8080
      - path: /auth
        backend:
          serviceName: keycloak-external
          servicePort: 8080

```

Which seems to at least get me rid of 308 redirect error. I am not sure how come it was working working with different values in hosts and host. And I am not sure how it fixed it.

But now I am stuck in a different issue, When I am trying to login - I am getting invalid redirect URI error.

![image](https://user-images.githubusercontent.com/19988460/43761972-4e00a8d6-9a44-11e8-9451-6302590f27b5.png)

Not sure what could cause this, Are the ports not forwarding properly.
