### ISSUE TITLE
Last mile encryption for keycloak not working

### ISSUE THREAD

**Issue by abhishekraghav** [galexrt/kubernetes-keycloak#3]
Hi @galexrt 

I tried the approach you suggested for enabling SSL on keycloak and to add a mount of the certs to the keycloak statefulSet.

> Yes the setup is terminating SSL at the LB.
> You would need to add a mount of the certs to the Keycloak StatefulSet and tell your Ingress Controller to let SSL "passthrough" and also go to the "backend" (Keycloak Service).
> Additionally you need to modify the Keycloak "config file" standalone-ha.xml (the config used here can be found here https://github.com/galexrt/kubernetes-keycloak/blob/master/configmap.yaml#L60-L706)...

To achieve that I initially though to put encoded certs and key in secret.yaml and refer that in stateful set. I could get those certs on keycloak pods but since keycloak requires a java keystore specifically, just certificate was not enough.
Then I found that kubertenes 1.10 supports adding binary data in config map. So I created a java keystore using the key pair I generated and used this command to create a Config map with binary data in it:
`kubectl create configmap keystore-cm --from-file=keycloak-keystore=keycloak-vault.jks`

Here keycloak-keystore is the key and jks file is the value.
and then I refered it into my statefulset like this:-

```
---
apiVersion: apps/v1
# Change to apps/v1beta2 for K8s < 1.9
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
      - name: keycloak-scripts
        projected:
          sources:
          - configMap:
              name: keycloak-scripts-cm
              items:
              - key: run.sh
                path: run.sh
                mode: 0755
              - key: standalone-ha.xml
                path: standalone-ha.xml
                mode: 0644
      #- name: sslcerts
      #  secret:
      #    secretName: certificates
      - name: kc-keystore
        projected:
          sources:
          - configMap:
              name: keystore-cm
              items:
              - key: keycloak-keystore
                path: keycloak-keystore
                mode: 0644
      containers:
        - name: keycloak
          image: jboss/keycloak:3.4.3.Final
          ports:
            - name: https
              containerPort: 8443
            - name: management
              containerPort: 9090
            - name: jgroups-tcp
              containerPort: 7600
            - name: jgroups-tcp-fd
              containerPort: 57600
            - name: jgroups-udp
              containerPort: 55200
              protocol: UDP
            - name: jgroups-udp-mc
              containerPort: 45688
              protocol: UDP
            - name: jgroups-udp-fd
              containerPort: 54200
              protocol: UDP
            - name: modcluster
              containerPort: 23364
            - name: modcluster-udp
              containerPort: 23364
              protocol: UDP
            - name: txn-recovery-ev
              containerPort: 4712
            - name: txn-status-mgr
              containerPort: 4713
          envFrom:
          - configMapRef:
              name: keycloak-env    
          - secretRef:
              name: keycloak-secret
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /scripts/run.sh
          args: []
          volumeMounts:
          - name: keycloak-scripts
            mountPath: "/scripts"
            readOnly: true
          #- name: sslcerts
          #  mountPath: "/opt/certs"
          #  readOnly: true
          - name: kc-keystore
            mountPath: "/opt/keystore"
            readOnly: true
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 60
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 7
            timeoutSeconds: 60
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "750m"
              memory: "1Gi"
```

But after I deploy this, I am getting below errors, not sure whether this is the correct way to mount a keystore or not.

Logs 
```
$ kubectl describe pods keycloak-0
Name:           keycloak-0
Namespace:      secdev
Node:           ip-172-31-39-102.ec2.internal/172.31.39.102
Start Time:     Fri, 17 Aug 2018 00:19:22 +0530
Labels:         app=keycloak
                controller-revision-hash=keycloak-7769cbf5f
                statefulset.kubernetes.io/pod-name=keycloak-0
Annotations:    <none>
Status:         Running
IP:             172.31.38.226
Controlled By:  StatefulSet/keycloak
Containers:
  keycloak:
    Container ID:  docker://8d33bfdead23a75f7fa6b705deebc06486a67f9fa775505ab9043d1310e2e56a
    Image:         jboss/keycloak:3.4.3.Final
    Image ID:      docker-pullable://jboss/keycloak@sha256:518aaa87ecd1492d4bd7f7d0df6c7bb856a37c89d323c110ebc4835860a4de82
    Ports:         8443/TCP, 9090/TCP, 7600/TCP, 57600/TCP, 55200/UDP, 45688/UDP, 54200/UDP, 23364/TCP, 23364/UDP, 4712/TCP, 4713/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/UDP, 0/UDP, 0/TCP, 0/UDP, 0/TCP, 0/TCP
    Command:
      /scripts/run.sh
    State:          Running
      Started:      Fri, 17 Aug 2018 00:21:24 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 17 Aug 2018 00:20:10 +0530
      Finished:     Fri, 17 Aug 2018 00:21:24 +0530
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      750m
      memory:   1Gi
    Liveness:   http-get http://:8080/ delay=25s timeout=60s period=7s #success=1 #failure=3
    Readiness:  http-get http://:8080/ delay=10s timeout=60s period=10s #success=2 #failure=10
    Environment Variables from:
      keycloak-env     ConfigMap  Optional: false
      keycloak-secret  Secret     Optional: false
    Environment:
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /opt/keystore from kc-keystore (ro)
      /scripts from keycloak-scripts (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-86xtj (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  keycloak-scripts:
  <unknown>
  kc-keystore:
  <unknown>
  default-token-86xtj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-86xtj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                                    Message
  ----     ------                 ----              ----                                    -------
  Normal   Scheduled              2m                default-scheduler                       Successfully assigned keycloak-0 to ip-172-31-39-102.ec2.internal
  Normal   SuccessfulMountVolume  2m                kubelet, ip-172-31-39-102.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-86xtj"
  Normal   SuccessfulMountVolume  2m                kubelet, ip-172-31-39-102.ec2.internal  MountVolume.SetUp succeeded for volume "keycloak-scripts"
  Normal   SuccessfulMountVolume  2m                kubelet, ip-172-31-39-102.ec2.internal  MountVolume.SetUp succeeded for volume "kc-keystore"
  Warning  BackOff                1m (x2 over 1m)   kubelet, ip-172-31-39-102.ec2.internal  Back-off restarting failed container
  Normal   Pulled                 1m (x3 over 2m)   kubelet, ip-172-31-39-102.ec2.internal  Container image "jboss/keycloak:3.4.3.Final" already present on machine
  Normal   Created                1m (x3 over 2m)   kubelet, ip-172-31-39-102.ec2.internal  Created container
  Normal   Started                1m (x3 over 2m)   kubelet, ip-172-31-39-102.ec2.internal  Started container
  Warning  Unhealthy              57s (x3 over 1m)  kubelet, ip-172-31-39-102.ec2.internal  Liveness probe failed: Get http://172.31.38.226:8080/: dial tcp 172.31.38.226:8080: getsockopt: connection refused
  Warning  Unhealthy              30s (x8 over 2m)  kubelet, ip-172-31-39-102.ec2.internal  Readiness probe failed: Get http://172.31.38.226:8080/: dial tcp 172.31.38.226:8080: getsockopt: connection refused

```

Am I going the right direction. Do you see any issues is the way I am setting up the keystore here.

Thanks.

**Comment by galexrt** [comment]
@abhishekraghav As I wrote you need to tell your Ingress to not terminate SSL and passthrough the SSL connections to the Pod(s) directly. The ingress controller then needs the certs to do SNI/Host header "detection" to see where the traffic needs to go. This can be done using an annotation in most cases.

Also you need to update your probes to the SSL port and use TLS/SSL for them.

**Comment by abhishekraghav** [comment]
Thanks for the quick reply @galexrt 
Please find my questions inline:-

> As I wrote you need to tell your Ingress to not terminate SSL and passthrough the SSL connections to the Pod(s) directly. The ingress controller then needs the certs to do SNI/Host header "detection" to see where the traffic needs to go. This can be done using an annotation in most cases.

Can you suggest which  annotation will best fit for this scenario. 
I added an annotation i.e. ingress.kubernetes.io/ssl-passthrough: "true" not sure is it enough to achieve this. Please suggest the changes in the below INGRESS object to let SSL passthrough.


```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-examplecom
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - keycloak.secdev.pocpcf.com
    secretName: tls-com-pocpcf-keycloak
  rules:
  - host: keycloak.secdev.pocpcf.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-external
          servicePort: 8443
      - path: /auth
        backend:
          serviceName: keycloak-external
          servicePort: 8443

```

> The ingress controller then needs the certs to do SNI/Host header "detection" to see where the traffic needs to go

Do I need to pass the SSL certs to my ingress. How to do that. Do I need one cert provisioned, with CN=keycloak.secdev.pocpcf.com


> Also you need to update your probes to the SSL port and use TLS/SSL for them.

Not sure, I understood this part. Are you talking about enabling SSL on keycloak as told in the previous thread. 

Sorry for asking too much !!!

Thanks.

**Comment by galexrt** [comment]
About the Ingress controller SSL passthrough annotation (using SNI if applicable):
Read up on your Ingress controller if SSL passthrough (+ SNI) is a) supported and b) available as an annotation configuration.
The Ingress controller your are using should have docs about that if not, they probably have an issue tracker to ask for docs/help about it.
The docs should also contain if the Ingress controller need the cert(s) and key(s) of the domain to be able to do SSL passthrough with SNI.

If your Keycloak is only speaking HTTPS you need to tell Kubernetes to make the liveness and readiness probe using https also and the "new" SSL port, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#httpgetaction-v1-core `scheme`.

**Comment by abhishekraghav** [comment]
@galexrt  Thanks for your valuable suggestion.

I have an architecture, where there is an AWS LB on the edge, which redirects the traffic to my NGINX controller and then the traffic goes to my internal keycloak pods.

I went through the NGINX ingress user guide and I found something interesting here.
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#ssl-passthrough and

https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#secure-backends-deprecated-since-0180

Which kind of satisfies my purpose of doing SSL passthrough.

So the final Ingress controller look like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-examplecom
  annotations:
    #https://docs.giantswarm.io/guides/advanced-ingress-configuration/#ssl-passthrough
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #By default NGINX uses plain HTTP to reach the services. Adding the annotation
    #nginx.ingress.kubernetes.io/secure-backends: "true" in the Ingress rule changes the protocol to HTTPS.
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: keycloak.secdev.pocpcf.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-external
          servicePort: 8443
```
Here I configured my keycloak to listen on SSL (8443) and 8080 both.  So I guess I need not to update the liveliness or readiness probe. For keycloak I am using self signed certificates. And on AWS LB anyway we have a public facing cert.

So With this setup, here the termination is happening twice. One at AWS LB and other on the POD(keycloak) itself.

With this configuration, I believe I am able to achieve all traffic encrypted throughout.

Moreover I did not see any configuration for SNI in NGINX ingress user guide.

Now, is there a way , I can validate whether the data on private network is encrypted. Also, does this configuration looks good to you. I guess enabling TLS-all should not hamper with the clustering etc. 

Thanks.
